### ISSUE TITLE
Using GPT as shown in the paper

### ISSUE THREAD

**Issue by MikeDoes** [theblackcat102/language-models-are-knowledge-graphs-pytorch#10]
I am interested in using GPT as the main model as BERT is not performing too well.

Has it been implemented? Otherwise I am ready to implement it myself. Please let me know

**Comment by MikeDoes** [comment]
Oh I found it here. Turns out the choices are:

 'bert-large-uncased', 'bert-large-cased', 'bert-base-uncased', 'bert-base-cased', 'gpt2', 'gpt2-medium', 'gpt2-large', 'gpt2-xl'

**Comment by MikeDoes** [comment]
I attempted to run it with the gpt2-xl parameters, however I got the following error:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/content/language-models-are-knowledge-graphs-pytorch/process.py", line 29, in bfs
    return BFS(s, end, graph, max_size, black_list_relation)
  File "/content/language-models-are-knowledge-graphs-pytorch/utils.py", line 19, in BFS
    visited = [False] * (max(graph.keys())+100)
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "extract.py", line 74, in <module>
    for triplets in parse_sentence(sent.text, tokenizer, encoder, nlp, use_cuda=use_cuda):
  File "/content/language-models-are-knowledge-graphs-pytorch/process.py", line 94, in parse_sentence
    for output in pool.imap_unordered(bfs, params):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/content/language-models-are-knowledge-graphs-pytorch/process.py", line 29, in bfs
    return BFS(s, end, graph, max_size, black_list_relation)
  File "/content/language-models-are-knowledge-graphs-pytorch/utils.py", line 19, in BFS
    visited = [False] * (max(graph.keys())+100) 
ValueError: max() arg is an empty sequence

**Comment by MikeDoes** [comment]
Also tried running it with just gpt2-large, same error and empty output file

**Comment by lingyu123-su** [comment]
got this error too

**Comment by lingyu123-su** [comment]
下面是一些不严谨的推论。
我在使用gpt2-medium时也遇到了同样的问题，在推理过程中，triplet['c‘]总是等于0.
我认为这是gpt2-medium的注意力矩阵的问题，和bert不同的是，它的注意力矩阵是一个下三角矩阵，在代码实现时，作者似乎把它当做上三角矩阵处理了。
我的做法是，在process.py，parse_sentence函数中，build_graph之前加上了下面的代码：
if 'GPT2' in tokenizer_name:
        merged_attention = merged_attention.T
现在，triplet['c']有数据了。
我不确定的是，这样在数学上是否严谨，以及是否会影响实验结果。
