### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by molyswu** [theblackcat102/language-models-are-knowledge-graphs-pytorch#2]
Hi,
python extract.py examples/bob_dylan.txt bert-large-cased-bob_dynlan.jsonl --language_model bert-large-cased --use_cuda true
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
Traceback (most recent call last):
  File "extract.py", line 3, in <module>
    from mapper import Map, deduplication
  File "language-models-are-knowledge-graphs-pytorch/mapper.py", line 5, in <module>
    emb = GenericLookup("entity_word_embedding", save_dir=sqlite_path, table_name="embeddings")
  File "anaconda3/lib/python3.6/site-packages/REL/db/generic.py", line 36, in __init__
    self.db = self.initialize_db(path_db, table_name, columns)
  File "anaconda3/lib/python3.6/site-packages/REL/db/base.py", line 41, in initialize_db
    db = sqlite3.connect(fname, isolation_level=None)
sqlite3.OperationalError: unable to open database file

thanks

**Comment by nidharap** [comment]
Check my solution here - https://github.com/theblackcat102/language-models-are-knowledge-graphs-pytorch/issues/1
